spring:
  datasource:
    url: jdbc:postgresql://postgres-service:5432/db
    username: vagrant
    password: vagrant
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
# show_sql: true
        format_sql: true
  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: vagrant
    password: vagrant
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace