Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.define "vm1" do |vm1|
      vm1.vm.box = "ubuntu/bionic64"
      vm1.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
      vm1.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: true
      vm1.vm.hostname = "vm1"
      vm1.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
      vm1.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "../ansible/master_playbook.yml"
      end
    end
  
    config.vm.define "vm2" do |vm2|
      vm2.vm.box = "ubuntu/bionic64"
      vm2.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
      vm2.vm.network "private_network", ip: "192.168.50.11", virtualbox__intnet: true
      vm2.vm.hostname = "vm2"
      vm2.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
      vm2.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "../ansible/worker_playbook.yml"
      end
    end
end
  