apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb-config
data:
  init.sql: |
    CREATE TABLE user_table (
        user_id BIGINT NOT NULL,
        name VARCHAR(255),
        PRIMARY KEY (user_id)
    );
    CREATE TABLE alarms (
        alarm_id BIGINT NOT NULL,
        creation_timestamp TIMESTAMP(6),
        request_timestamp TIMESTAMP(6),
        reservation_timestamp TIMESTAMP(6),
        user_id BIGINT,
        content VARCHAR(255),
        title VARCHAR(255),
        url VARCHAR(255),
        uuid VARCHAR(255),
        PRIMARY KEY (alarm_id),
        FOREIGN KEY (user_id) REFERENCES user_table(user_id)
    );
    CREATE SEQUENCE alarms_seq START 1;
    CREATE SEQUENCE user_table_seq START 1;
    ALTER SEQUENCE user_table_seq INCREMENT BY 50;
    ALTER SEQUENCE alarms_seq INCREMENT BY 50;


