apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15.4
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: db
        - name: POSTGRES_USER
          value: vagrant
        - name: POSTGRES_PASSWORD
          value: vagrant
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: postgresql-initdb
      volumes:
        - name: postgresql-initdb
          configMap:
            name: postgresql-initdb-config
